#!/usr/bin/env python3
# SPDX-FileCopyrightText: JR Lanteigne <root@dnim.dev>
# SPDX-License-Identifier: GPL-3.0-or-later
"""Report layout coverage: how many boards sharkfin can actually render.

Usage: tools/coverage.py [--json] [--markdown [PATH]]

--markdown regenerates the exhaustive per-board support list
(docs/BOARDS.md by default) from the registry, so the list can never
drift from what the app actually does.
"""

import argparse
import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEVICES = ROOT / "app/src-tauri/data/devices.json"
CONFIRMED = ROOT / "app/src-tauri/data/confirmed.json"
VENDOR_LAYOUTS = ROOT / "app/src/lib/layouts/vendor"
CANONICAL = {"Common80_k72x86"}

# Mirrors KNOWN_FAMILIES in app/src-tauri/src/registry.rs. Anything else is
# read-only. Keep the two in step or this report describes a different app.
WRITABLE_FAMILIES = ("yc500", "gen2")


def layouts_present() -> tuple[set[str], set[str]]:
    """Layouts that draw out of the box, and geometry-only layouts.

    A file whose keys carry matrix slots renders as-is. A file with geometry
    but no slots renders only after the app matches it against the connected
    board's keymap and the owner confirms the picture; the Unknown
    placeholder is excluded because it describes no particular board.
    """
    baked = set(CANONICAL)
    geometry = set()
    if VENDOR_LAYOUTS.is_dir():
        for p in VENDOR_LAYOUTS.glob("*.json"):
            keys = json.loads(p.read_text("utf-8")).get("keys", [])
            if any(k.get("matrixIndex") is not None for k in keys):
                baked.add(p.stem)
            elif p.stem != "Unknown":
                geometry.add(p.stem)
    return baked, geometry


def label(d: dict) -> str:
    """Same rule as deviceLabel in app/src/lib/brands.ts: some vendor
    display names already carry the brand, and prefixing it again reads as
    "YUNZII YUNZII B75 PRO"."""
    name = d.get("displayName") or d["name"]
    brand = (d.get("company") or d.get("vendor") or "").strip()
    if brand and not name.lower().startswith(brand.lower()):
        return f"{brand} {name}"
    return name


def write_markdown(
    devices: list[dict], baked: set[str], geometry: set[str], path: Path
) -> None:
    rows = sorted(devices, key=lambda d: (label(d).lower(), d["id"]))
    total = len(rows)
    drawn = sum(1 for d in rows if d["keyLayout"] in baked)
    auto = sum(1 for d in rows if d["keyLayout"] in geometry)
    writable = sum(1 for d in rows if d.get("family") in WRITABLE_FAMILIES)
    confirmed = {c["id"]: c for c in json.loads(CONFIRMED.read_text("utf-8"))}

    out = [
        "# Board support",
        "",
        "Generated by `tools/coverage.py --markdown` from the device",
        "registry — do not edit by hand.",
        "",
        f"{total} boards. **Write** means sharkfin can change settings on it;",
        "blank means read-only. **Draw** says how the board is pictured:",
        "**yes** is drawn out of the box, **auto** is drawn once sharkfin has",
        "matched the picture against your board and you have confirmed it,",
        "blank is a plain grid of key slots. All three work the same.",
        "**Confirmed** names the issue where an owner sent a read sweep from",
        "the board itself; blank means the entry rests on the vendor's data.",
        "",
        f"| | count |",
        f"|---|---:|",
        f"| total | {total} |",
        f"| writable | {writable} |",
        f"| drawn | {drawn} |",
        f"| drawn after confirmation | {auto} |",
        f"| confirmed on hardware | {len(confirmed)} |",
        "",
        "| board | id | usb | family | write | draw | confirmed |",
        "|---|---|---|---|---|---|---|",
    ]
    for d in rows:
        fam = d.get("family", "unknown")
        out.append(
            "| {} | {} | {:04x}:{:04x} | {} | {} | {} | {} |".format(
                label(d),
                d["id"],
                d["vendorId"],
                d["productId"],
                fam,
                "yes" if fam in WRITABLE_FAMILIES else "",
                "yes" if d["keyLayout"] in baked else "auto" if d["keyLayout"] in geometry else "",
                f"#{confirmed[d['id']]['issue']}" if d["id"] in confirmed else "",
            )
        )
    out.append("")
    path.write_text("\n".join(out), "utf-8")
    print(f"wrote {path.relative_to(ROOT)} ({total} boards)")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--json", action="store_true")
    ap.add_argument(
        "--markdown",
        nargs="?",
        const=str(ROOT / "docs/BOARDS.md"),
        metavar="PATH",
    )
    args = ap.parse_args()

    devices = json.loads(DEVICES.read_text("utf-8"))
    baked, geometry = layouts_present()

    if args.markdown:
        write_markdown(devices, baked, geometry, Path(args.markdown))
        return

    writable = [d for d in devices if d.get("family") in WRITABLE_FAMILIES]
    have = baked | geometry

    def covered(ds, names):
        return sum(1 for d in ds if d["keyLayout"] in names)

    missing_by_layout = Counter(
        d["keyLayout"]
        for d in writable
        if d["keyLayout"] not in have and d["keyLayout"] != "Unknown"
    )

    report = {
        "boards": len(devices),
        "boardsDrawn": covered(devices, baked),
        "boardsDrawnAfterConfirmation": covered(devices, geometry),
        "writable": len(writable),
        "writableDrawn": covered(writable, baked),
        "layoutFiles": len(have),
        "slotlessLayouts": len(geometry),
        "missingWritableLayouts": dict(missing_by_layout.most_common()),
    }

    if args.json:
        print(json.dumps(report, indent=2))
        return

    n = report["boards"]
    undrawn = n - report["boardsDrawn"] - report["boardsDrawnAfterConfirmation"]
    print(f"boards in the registry       {n}")
    print(f"  drawn out of the box         {report['boardsDrawn']}")
    print(f"  drawn after confirmation     {report['boardsDrawnAfterConfirmation']}"
          f"  ({undrawn} grid only)")
    print(f"  writable (verified family)   {report['writable']}"
          f"  ({n - report['writable']} read-only)")
    print(f"layout files on disk         {report['layoutFiles']}"
          f"  ({report['slotlessLayouts']} without slot data)")
    if missing_by_layout:
        print(f"\nlayouts still needed for writable boards ({len(missing_by_layout)}):")
        for name, n in missing_by_layout.most_common():
            brands = sorted(
                {
                    d.get("company") or d.get("vendor") or "?"
                    for d in writable
                    if d["keyLayout"] == name
                }
            )
            print(f"  {name:34s} {n:2d}  {', '.join(brands)}")


if __name__ == "__main__":
    main()
