#!/usr/bin/env python3
# SPDX-FileCopyrightText: JR Lanteigne <root@dnim.dev>
# SPDX-License-Identifier: GPL-3.0-or-later
"""Report layout coverage: how many boards sharkfin can actually render.

Usage: tools/coverage.py [--json] [--markdown [PATH]]

--markdown regenerates the exhaustive per-board support list
(docs/BOARDS.md by default) from the registry, so the list can never
drift from what the app actually does.
"""

import argparse
import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEVICES = ROOT / "app/src-tauri/data/devices.json"
VENDOR_LAYOUTS = ROOT / "app/src/lib/layouts/vendor"
CANONICAL = {"Common80_k72x86"}


def layouts_present() -> set[str]:
    have = set(CANONICAL)
    if VENDOR_LAYOUTS.is_dir():
        have |= {p.stem for p in VENDOR_LAYOUTS.glob("*.json")}
    return have


def label(d: dict) -> str:
    name = d.get("displayName") or d["name"]
    brand = d.get("company") or d.get("vendor") or ""
    return f"{brand} {name}".strip()


def write_markdown(devices: list[dict], have: set[str], path: Path) -> None:
    rows = sorted(devices, key=lambda d: (label(d).lower(), d["id"]))
    total = len(rows)
    drawn = sum(1 for d in rows if d["keyLayout"] in have)
    writable = sum(1 for d in rows if d.get("family") in ("yc500", "gen2"))

    out = [
        "# Board support",
        "",
        "Generated by `tools/coverage.py --markdown` from the device",
        "registry — do not edit by hand.",
        "",
        f"{total} boards. **Write** means sharkfin can change settings on it;",
        "blank means read-only. **Draw** means sharkfin has layout data to",
        "render the board; the rest show a slot grid and work the same.",
        "",
        f"| | count |",
        f"|---|---:|",
        f"| total | {total} |",
        f"| writable | {writable} |",
        f"| drawable | {drawn} |",
        "",
        "| board | id | usb | family | write | draw |",
        "|---|---|---|---|---|---|",
    ]
    for d in rows:
        fam = d.get("family", "unknown")
        out.append(
            "| {} | {} | {:04x}:{:04x} | {} | {} | {} |".format(
                label(d),
                d["id"],
                d["vendorId"],
                d["productId"],
                fam,
                "yes" if fam in ("yc500", "gen2") else "",
                "yes" if d["keyLayout"] in have else "",
            )
        )
    out.append("")
    path.write_text("\n".join(out), "utf-8")
    print(f"wrote {path.relative_to(ROOT)} ({total} boards)")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--json", action="store_true")
    ap.add_argument(
        "--markdown",
        nargs="?",
        const=str(ROOT / "docs/BOARDS.md"),
        metavar="PATH",
    )
    args = ap.parse_args()

    devices = json.loads(DEVICES.read_text("utf-8"))
    have = layouts_present()

    if args.markdown:
        write_markdown(devices, have, Path(args.markdown))
        return

    writable = [d for d in devices if d.get("family") == "yc500"]

    def covered(ds):
        return sum(1 for d in ds if d["keyLayout"] in have)

    missing_by_layout = Counter(
        d["keyLayout"]
        for d in writable
        if d["keyLayout"] not in have and d["keyLayout"] != "Unknown"
    )

    report = {
        "boards": len(devices),
        "boardsWithLayout": covered(devices),
        "writable": len(writable),
        "writableWithLayout": covered(writable),
        "layoutFiles": len(have),
        "missingWritableLayouts": dict(missing_by_layout.most_common()),
    }

    if args.json:
        print(json.dumps(report, indent=2))
        return

    n = report["boards"]
    print(f"boards in the registry       {n}")
    print(f"  can be drawn                 {report['boardsWithLayout']}"
          f"  ({n - report['boardsWithLayout']} lack layout data)")
    print(f"  writable (verified family)   {report['writable']}"
          f"  ({n - report['writable']} read-only)")
    print(f"  both                         {report['writableWithLayout']}")
    print(f"layout files on disk         {report['layoutFiles']}")
    if missing_by_layout:
        print(f"\nlayouts still needed for writable boards ({len(missing_by_layout)}):")
        for name, n in missing_by_layout.most_common():
            brands = sorted(
                {
                    d.get("company") or d.get("vendor") or "?"
                    for d in writable
                    if d["keyLayout"] == name
                }
            )
            print(f"  {name:34s} {n:2d}  {', '.join(brands)}")


if __name__ == "__main__":
    main()
