// SPDX-FileCopyrightText: JR Lanteigne <root@dnim.dev>
// SPDX-License-Identifier: GPL-3.0-or-later
// Writes dist-web/sw.js: a service worker that precaches the whole build so
// the browser app loads with no network. Runs after `vite build`; the cache
// name is a digest of every file, so any change ships as a new cache and the
// old one is deleted on activation.
import { createHash } from "node:crypto";
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";

const root = path.resolve(process.cwd(), "dist-web");
const files = [];
(function walk(dir) {
  for (const name of readdirSync(dir)) {
    const p = path.join(dir, name);
    if (statSync(p).isDirectory()) walk(p);
    else files.push(p);
  }
})(root);
files.sort();

const hash = createHash("sha256");
const assets = [];
for (const f of files) {
  const rel = "/" + path.relative(root, f).split(path.sep).join("/");
  // Packaging strips the two template svgs before serving, and a single
  // missing file fails the whole precache, so they must not be listed.
  if (rel === "/sw.js" || rel === "/tauri.svg" || rel === "/vite.svg") continue;
  hash.update(rel);
  hash.update(readFileSync(f));
  assets.push(rel === "/index.html" ? "/" : rel);
}
const version = "sharkfin-" + hash.digest("hex").slice(0, 12);

const sw = `// generated by scripts/gen-sw.mjs; do not edit
const VERSION = ${JSON.stringify(version)};
const ASSETS = ${JSON.stringify(assets)};

self.addEventListener("install", (e) => {
  e.waitUntil(caches.open(VERSION).then((c) => c.addAll(ASSETS)));
});

// No clients.claim(): the first-ever page stays uncontrolled, so
// controllerchange only ever means the user accepted an update.
self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(keys.filter((k) => k !== VERSION).map((k) => caches.delete(k))),
      ),
  );
});

self.addEventListener("message", (e) => {
  if (e.data === "skip-waiting") self.skipWaiting();
});

self.addEventListener("fetch", (e) => {
  const url = new URL(e.request.url);
  if (e.request.method !== "GET" || url.origin !== location.origin) return;
  const key = e.request.mode === "navigate" ? "/" : url.pathname;
  e.respondWith(caches.match(key).then((hit) => hit || fetch(e.request)));
});
`;

writeFileSync(path.join(root, "sw.js"), sw);
console.log(`sw.js: ${assets.length} assets, cache ${version}`);
